name: Publish

on:
  push:
    branches:
      - alpha

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Get current branch
        run: |
          EGO_BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo $EGO_BRANCH_NAME
      - name: Output current branch
        run: |
          EGO_BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch name: $EGO_BRANCH_NAME"
          echo "Repo: $GITHUB_REPOSITORY"
