name: Check pull requests

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    paths:
      - "packages/http-controllers/**"

defaults:
  run:
    working-directory: "packages/http-controllers"

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: NPM 9 install
        run: npm install -g npm@9
      - name: Install dependencies
        run: npm install --force
      - name: Lint code
        run: npm run lint
      - name: Build library
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Generate documentation
        run: npm run docs:generate
